---
- name: Install postgresql yum repository
  package:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Override plpython_packages for CentOS 7
  set_fact:
    plpython_packages:
      12:
        - postgresql12-plpython
      11:
        - postgresql11-plpython
      10:
        - postgresql10-plpython
  when: ansible_distribution_major_version == "7"
